[package]
name = "day_13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util", version = "0.0.0" }
pest = "2.5.1"
pest_derive = "2.5.1"